export const currentDate = new Date()
// export const day = time.getDate()
// export const month = time.getMonth()
// export const year = time.getFullYear()
export const time = currentDate.getHours()
export const minutes = currentDate.getMinutes()